### ISSUE TITLE
Unsupported parameters for (opengear.om.om_services) module: config.syslog.multi_field_identifier

### ISSUE THREAD

**Issue by coolcps** [opengear/ansible-ng#17]
I saw that there was another issue related to this for the ssh credentials, but looks like the same issue for config.syslog.  I tried to just add in the new field to the arg_parse like so:

```
                                                    'type': 'dict'},
                                            'syslog': {'elements': 'dict',
                                                       'options': {'address': {'type': 'str'},
                                                                   'description': {'type': 'str'},
                                                                   'id': {'type': 'str'},
                                                                   'min_severity': {'type': 'str'},
                                                                   'port': {'type': 'int'},
                                                                   'port_logging_enabled': {'type': 'bool'},
                                                                   'protocol': {'type': 'str'},
                                                                   'multi_field_identifier': {'type': 'str'}},
                                                       'type': 'list'}},
```
But then I get this error:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'name'
fatal: [device]: FAILED! => {
    "changed": false,
    "rc": 1
}

MSG:

MODULE FAILURE
See stdout/stderr for the exact error


MODULE_STDERR:

Traceback (most recent call last):
  File "/links/home/user/.ansible/tmp/ansible-local-1346626rk48ckv1/ansible-tmp-1729615461.8124921-1346632-270858861926678/AnsiballZ_om_services.py", line 107, in <module>
    _ansiballz_main()
  File "/links/home/user/.ansible/tmp/ansible-local-1346626rk48ckv1/ansible-tmp-1729615461.8124921-1346632-270858861926678/AnsiballZ_om_services.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/links/home/user/.ansible/tmp/ansible-local-1346626rk48ckv1/ansible-tmp-1729615461.8124921-1346632-270858861926678/AnsiballZ_om_services.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.opengear.om.plugins.modules.om_services', init_globals=dict(_module_fqn='ansible_collections.opengear.om.plugins.modules.om_services', _modlib_path=modlib_path),
  File "/usr/local/tools/python/python-3.10.8/lib/python3.10/runpy.py", line 224, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/local/tools/python/python-3.10.8/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/local/tools/python/python-3.10.8/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_opengear.om.om_services_payload_yjowlvo1/ansible_opengear.om.om_services_payload.zip/ansible_collections/opengear/om/plugins/modules/om_services.py", line 389, in <module>
  File "/tmp/ansible_opengear.om.om_services_payload_yjowlvo1/ansible_opengear.om.om_services_payload.zip/ansible_collections/opengear/om/plugins/modules/om_services.py", line 384, in main
  File "/tmp/ansible_opengear.om.om_services_payload_yjowlvo1/ansible_opengear.om.om_services_payload.zip/ansible_collections/opengear/om/plugins/module_utils/network/om/config/services/services.py", line 95, in execute_module
  File "/tmp/ansible_opengear.om.om_services_payload_yjowlvo1/ansible_opengear.om.om_services_payload.zip/ansible_collections/opengear/om/plugins/module_utils/network/om/config/services/services.py", line 131, in set_config
  File "/tmp/ansible_opengear.om.om_services_payload_yjowlvo1/ansible_opengear.om.om_services_payload.zip/ansible_collections/opengear/om/plugins/module_utils/network/om/config/services/services.py", line 145, in set_state
  File "/tmp/ansible_opengear.om.om_services_payload_yjowlvo1/ansible_opengear.om.om_services_payload.zip/ansible_collections/opengear/om/plugins/module_utils/network/om/config/services/services.py", line 200, in _state_overridden
  File "/tmp/ansible_opengear.om.om_services_payload_yjowlvo1/ansible_opengear.om.om_services_payload.zip/ansible_collections/opengear/om/plugins/module_utils/network/om/config/services/services.py", line 40, in get_name_id_map
KeyError: 'name'

```

And while I haven't tested it, it looks like static_routes will haave the same issue with multi_field_identifier.

**Comment by LachyTech** [comment]
I've just enhanced the services modules as part of issue #32 which supports the current API as of firmware 25.11.9, so I believe this issue can be closed. If you would like to use the current version of the collection, please upgrade your device to latest firmware and install this collection from source. There are comprehensive examples in `examples/playbooks`.

Limited release of the `opengear.ng` collection on Ansible Galaxy will be available soon.
